# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-30 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlexpander', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='url',
            name='final_url',
            field=models.URLField(max_length=250, null=models.URLField(max_length=250)),
        ),
        migrations.AddField(
            model_name='url',
            name='status',
            field=models.CharField(default='200', max_length=100),
        ),
        migrations.AddField(
            model_name='url',
            name='title',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='url',
            name='url',
            field=models.URLField(max_length=250),
        ),
    ]
