# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlexpander', '0002_auto_20160730_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='final_url',
            field=models.CharField(max_length=250, null=models.URLField(max_length=250)),
        ),
    ]
